# Generated by Django 4.1 on 2024-12-02 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_department_stud_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='fac_id',
            field=models.ForeignKey(limit_choices_to={'is_fac': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stud',
            name='stud_id',
            field=models.ForeignKey(limit_choices_to={'is_stud': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
