# Generated by Django 5.1.3 on 2024-12-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_staff_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
