# Generated by Django 5.1.3 on 2024-12-04 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_remove_stud_stud_id_delete_staff_delete_stud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_id', models.IntegerField()),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(limit_choices_to={'is_fac': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
