# Generated by Django 5.1.3 on 2024-12-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
