# Generated by Django 5.1.3 on 2024-12-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_delete_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
