# Generated by Django 5.1.3 on 2024-12-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_user_fname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fname',
        ),
    ]
