# Generated by Django 4.2.10 on 2024-12-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='sem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
