# Generated by Django 4.2.10 on 2024-12-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('programme', models.CharField(default='Master of Computer Applications', max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=255)),
                ('credits', models.FloatField()),
                ('ca_marks', models.IntegerField(verbose_name='Continuous Assessment Marks')),
                ('ese_marks', models.IntegerField(verbose_name='End Semester Evaluation Marks')),
                ('total_marks', models.IntegerField()),
                ('grade_point', models.FloatField()),
                ('credit_point', models.FloatField()),
                ('result', models.CharField(choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1)),
                ('sgpa', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=20)),
            ],
        ),
    ]
