# Generated by Django 5.1.3 on 2024-12-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_timetable_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='user',
        ),
    ]
