# Generated by Django 5.1.3 on 2024-12-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_studentresult_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
