# Generated by Django 5.1.3 on 2024-12-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_studentresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='grade_point',
        ),
    ]
